# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  push:
    branches: [ "main", "ci" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

env:
    AWS_DEFAULT_REGION: 'us-east-1'

jobs:
  deploy-website:
    name: Deploy Website
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Deps
        uses: actions/setup-python@v4
        with:
          python-version: '3.9.16'
          cache: 'pip'
      - name: Update EC2 Files
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        run: |
          echo "$PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh -i  ~/.ssh/id_rsa -o StrictHostKeyChecking=no $USER@$HOST "./scripts/refresh-ec2.sh"
          rm  ~/.ssh/id_rsa
